server:
  port: 8888

spring:
  application:
    name: ConfigServer

  profiles:
    active: native # Use the native profile to read configuration from the local file system or classpath
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo